apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    spec:
      containers:
      - name: hello
        image: your-image-name
        command: ["echo"]
        args: ["Hello World"]
      restartPolicy: Never
  backoffLimit: 4
