name: CI/CD Pipeline

on:
  pull_request:
    branches: [ master ]  # Specify the branch where the PRs are made

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2  # Checkout the repository content

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Set the Python version to match the Dockerfile

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/pythia_nlp:${{ github.sha }} .

    # - name: Test Docker image
    #   run: |
    #     docker run --rm -d -p 8000:8000 ghcr.io/${{ github.repository }}/pythia_nlp:${{ github.sha }}
    #     sleep 10  # Wait for the server to start
    #     curl --fail http://localhost:8000/  # Replace this with an actual health-check endpoint if available

    - name: Log in to GitHub Container Registry
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      run: |
        docker push ghcr.io/${{ github.repository }}/pythia_nlp:${{ github.sha }}
