name: CI/CD Pipeline

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]  # Trigger on push to master as well

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Build and tag Docker image
      run: |
        docker build -t ghcr.io/kizyma/ml-ops-proj:${{ github.sha }} .
        docker tag ghcr.io/kizyma/ml-ops-proj:${{ github.sha }} ghcr.io/kizyma/ml-ops-proj:latest

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image with SHA tag
      run: |
        docker push ghcr.io/kizyma/ml-ops-proj:${{ github.sha }}

    - name: Push Docker image with latest tag
      if: github.ref == 'refs/heads/master'
      run: |
        docker push ghcr.io/kizyma/ml-ops-proj:latest
